### ISSUE TITLE
to_coco error, numpy binary incompatibility

### ISSUE THREAD

**Issue by pcicales** [bdd100k/bdd100k#122]
After running:

`python3 -m bdd100k.label.to_coco -l /redact/datasets/bdd100k/labels/det_20/det_train.json -o /redact/datasets/bdd100k/labels/det_20_coco/det_train.json --remove-ignore`

from the cloned git directory, I receive the following traceback:

`Traceback (most recent call last):
 File "/redact/anaconda3/envs/bdd100k/lib/python3.7/runpy.py", line 193, in _run_module_as_main
   "__main__", mod_spec)
 File "/redact/anaconda3/envs/bdd100k/lib/python3.7/runpy.py", line 85, in _run_code
   exec(code, run_globals)
 File "/redact/workspace/pycharm_projects/bdd100k/bdd100k/label/to_coco.py", line 12, in <module>
   from scalabel.label.coco_typing import AnnType, GtType, ImgType, VidType
 File "/redact/anaconda3/envs/bdd100k/lib/python3.7/site-packages/scalabel/__init__.py", line 3, in <module>
   from . import bot, label, tools
 File "/redact/anaconda3/envs/bdd100k/lib/python3.7/site-packages/scalabel/label/__init__.py", line 3, in <module>
   from . import coco_typing, from_coco, io, to_coco, typing
 File "/redact/anaconda3/envs/bdd100k/lib/python3.7/site-packages/scalabel/label/to_coco.py", line 11, in <module>
   from pycocotools import mask as mask_utils  # type: ignore
 File "/redact/anaconda3/envs/bdd100k/lib/python3.7/site-packages/pycocotools/mask.py", line 3, in <module>
   import pycocotools._mask as _mask
 File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject`

It appears that this is due to an older version of numpy being installed; I will test this on other labels and see if its specific to this label set.

**Comment by fyu** [comment]
This is because your install python libraries are depending on different numpy versions. You can resolve this issue by creating a clean virtual python environment and install all the required libraries with `pip install -r requirements.txt` from scratch.

**Comment by pcicales** [comment]
Hello @fyu , thank you for the wonderful dataset and rapid reply!

That is what I did using conda. Here is the version info:

`Python 3.7.10 (default, Feb 26 2021, 18:47:35)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> print(numpy.__version__)
1.19.5`

**Comment by fyu** [comment]
You have the right numpy version, but some of your libraries (maybe `pycocotools`) depends on a different version of numpy. A clean install usually solves the problem.

**Comment by pcicales** [comment]
Upgrading numpy to version 1.20.3 appears to have solved the problem. Perhaps 'pycocotools' has been updated with a newer version of numpy? Here is the output of the same corrected command:

'
(bdd100k) redact@redact:/redact/workspace/pycharm_projects/bdd100k$ python3 -m bdd100k.label.to_coco -i /redact/bdd100k/labels/det_20/det_train.json -o /redact/datasets/bdd100k/labels/det_20_coco/det_train.json
[2021-05-31 14:33:39,024 to_coco.py:577 main] Loading annotations...
[2021-05-31 14:34:37,101 to_coco.py:586 main] Start format converting...
100%|██████████████████████████████████████████████████████████████████████████| 69863/69863 [00:01<00:00, 53779.44it/s]
100%|███████████████████████████████████████████████████████████████████████████| 69863/69863 [00:10<00:00, 6383.82it/s]
[2021-05-31 14:34:49,386 to_coco.py:590 main] Saving converted annotations to disk...
[2021-05-31 14:35:12,709 to_coco.py:593 main] Finished!
'

**Comment by fyu** [comment]
> Upgrading numpy to version 1.20.3 appears to have solved the problem. Perhaps `pycocotools` has been updated with a newer version of numpy? 

Yes, `pycocotools` looks like the culprit.
