### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by liuliaocheng** [bdd100k/bdd100k#191]
Excuse me ，i want Convert "ins_seg_train.json" to coco，i used this command "python -m bdd100k.label.to_coco -m ins_seg -i ins_seg_train.json -o ins_seg_train_coco.json".
but the program error：
[2021-11-11 13:53:21,270 to_coco.py:537 main] Loading annotations...
[2021-11-11 13:53:31,594 to_coco.py:546 main] Start format converting...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7000/7000 [00:00<00:00, 46697.44it/s]
[2021-11-11 13:53:31,746 to_coco.py:321 bdd100k2coco_ins_seg] Collecting annotations...
  0%|                                                                                                                                                    | 0/7000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/stan/anaconda3/envs/labelme/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/stan/anaconda3/envs/labelme/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/stan/wkstion/labeltool/bdd100k/bdd100k/label/to_coco.py", line 557, in <module>
    main()
  File "/home/stan/wkstion/labeltool/bdd100k/bdd100k/label/to_coco.py", line 548, in main
    coco = convert_func(frames=frames, config=bdd100k_config.scalabel)
  File "/home/stan/wkstion/labeltool/bdd100k/bdd100k/label/to_coco.py", line 344, in bdd100k2coco_ins_seg
    image_anns.name.replace(".jpg", ".png"),
  File "/home/stan/anaconda3/envs/labelme/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

What should I do ~！thanks!

**Comment by liuliaocheng** [comment]
when i used this command "python -m bdd100k.label.to_coco -m ins_seg -i bdd100k_labels_images_val.json -o bdd100k_labels_images_val_coco.json".，the new problem is coming , like :
```

_[2021-11-11 13:59:01,102 to_coco.py:537 main] Loading annotations...
[2021-11-11 13:59:14,389 to_coco.py:546 main] Start format converting...
  0%|                                                                                                                                                   | 0/10000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/stan/anaconda3/envs/labelme/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/stan/anaconda3/envs/labelme/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/stan/wkstion/labeltool/bdd100k/bdd100k/label/to_coco.py", line 557, in <module>
    main()
  File "/home/stan/wkstion/labeltool/bdd100k/bdd100k/label/to_coco.py", line 547, in main
    frames = bdd100k_to_scalabel(dataset.frames, bdd100k_config)
  File "/home/stan/wkstion/labeltool/bdd100k/bdd100k/label/to_scalabel.py", line 58, in bdd100k_to_scalabel
    image_anns.labels[i], bdd100k_config, cat_name2id
  File "/home/stan/wkstion/labeltool/bdd100k/bdd100k/label/to_scalabel.py", line 35, in deal_bdd100k_category
    assert category_name in bdd100k_config.ignored_mapping
AssertionError_
```

i need request support, thank you！！！

**Comment by jakobjackson2016** [comment]
> Excuse me ，i want Convert "ins_seg_train.json" to coco，i used this command "python -m bdd100k.label.to_coco -m ins_seg -i ins_seg_train.json -o ins_seg_train_coco.json". but the program error： [2021-11-11 13:53:21,270 to_coco.py:537 main] Loading annotations... [2021-11-11 13:53:31,594 to_coco.py:546 main] Start format converting... 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7000/7000 [00:00<00:00, 46697.44it/s] [2021-11-11 13:53:31,746 to_coco.py:321 bdd100k2coco_ins_seg] Collecting annotations... 0%| | 0/7000 [00:00<?, ?it/s] Traceback (most recent call last): File "/home/stan/anaconda3/envs/labelme/lib/python3.7/runpy.py", line 193, in _run_module_as_main "**main**", mod_spec) File "/home/stan/anaconda3/envs/labelme/lib/python3.7/runpy.py", line 85, in _run_code exec(code, run_globals) File "/home/stan/wkstion/labeltool/bdd100k/bdd100k/label/to_coco.py", line 557, in main() File "/home/stan/wkstion/labeltool/bdd100k/bdd100k/label/to_coco.py", line 548, in main coco = convert_func(frames=frames, config=bdd100k_config.scalabel) File "/home/stan/wkstion/labeltool/bdd100k/bdd100k/label/to_coco.py", line 344, in bdd100k2coco_ins_seg image_anns.name.replace(".jpg", ".png"), File "/home/stan/anaconda3/envs/labelme/lib/python3.7/posixpath.py", line 80, in join a = os.fspath(a) TypeError: expected str, bytes or os.PathLike object, not NoneType
> 
> What should I do ~！thanks!

Were you able to solve this issue? Thanks @liuliaocheng
