### ISSUE TITLE
KeyError: 'frames'

### ISSUE THREAD

**Issue by huoguangdiandian** [bdd100k/bdd100k#229]
您好：
我在做评价结果的时候，碰到这个错误，请问是什么原因啊
python3 -m bdd100k.eval.run -t det -g ./jsons/det_val_cocofmt.json -r ./jsons/det.json
Traceback (most recent call last):
  File "/home/libo/anaconda3/envs/mmdetection/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/libo/anaconda3/envs/mmdetection/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/libo/workspace/object_detection/bdd100k/bdd100k/eval/run.py", line 295, in <module>
    run()
  File "/home/libo/workspace/object_detection/bdd100k/bdd100k/eval/run.py", line 218, in run
    gt_frames, result_frames = _load_frames(
  File "/home/libo/workspace/object_detection/bdd100k/bdd100k/eval/run.py", line 202, in _load_frames
    gt_frames = bdd100k_to_scalabel(load(gt_base, nproc).frames, config)
  File "/home/libo/anaconda3/envs/mmdetection/lib/python3.9/site-packages/scalabel-0.3.0rc2-py3.9.egg/scalabel/label/io.py", line 90, in load
    ret_cfg = process_file(inputs)
  File "/home/libo/anaconda3/envs/mmdetection/lib/python3.9/site-packages/scalabel-0.3.0rc2-py3.9.egg/scalabel/label/io.py", line 77, in process_file
    raw_frames.extend(content["frames"])
KeyError: 'frames'

**Comment by siyliepfl** [comment]
please check again your results format. you can read this doc for details: https://doc.scalabel.ai/format.html

**Comment by fyu** [comment]
@huoguangdiandian If you still have the problem, you can also paste a sample of your file, which can reproduce the issue.

**Comment by huoguangdiandian** [comment]
> 

@siyliepfl 要转成scalabel格式的json，我现在试着用scalabel中from_coco.py转换，但是会出现这样的问题
File "/home/libo/workspace/scalabel-master/scalabel/label/from_coco.py", line 9, in <module>
    from ..common.io import open_read_text
ImportError: attempted relative import with no known parent package
请问还有其他方法转合适吗

**Comment by siyliepfl** [comment]
The issue is related to your working root. You need to add the proper root path to your sys.path. Alternatively, you can run `python -m scalabel.label.from_coco -i your_coco_json -o results.json`

**Comment by huoguangdiandian** [comment]
> The issue is related to your working root. You need to add the proper root path to your sys.path. Alternatively, you can run `python -m scalabel.label.from_coco -i your_coco_json -o results.json`

thank you, the problem is solved!!!
