### ISSUE TITLE
EvalAI submission error!

### ISSUE THREAD

**Issue by chongweiliu** [bdd100k/bdd100k#322]
Hi, I have submit my results into the EvalAI for "BDD100K Multiple Object Tracking Challenge", and get the following error, which sounds like the version issue of pydantic. Could you figure it out?
`
Traceback (most recent call last):
  File "/code/scripts/workers/submission_worker.py", line 511, in run_submission
    submission_metadata=submission_serializer.data,
  File "/tmp/tmpebpw_c08/compute/challenge_data/challenge_1836/main.py", line 82, in evaluate
    bdd100k_config = load_label_config(CFG_FILE)
  File "/usr/local/lib/python3.7/site-packages/scalabel/label/io.py", line 188, in load_label_config
    config = Config(**cfg)
  File "/usr/local/lib/python3.7/site-packages/pydantic/main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 24 validation errors for Config
imageSize
  Field required [type=missing, input_value={'image_size': {'height':... {'name': 'bicycle'}]}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
attributes.0.tagPrefix
  Field required [type=missing, input_value={'name': 'crowd', 'type': 'switch', 'tag': 'c'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
attributes.0.tagSuffixes
  Field required [type=missing, input_value={'name': 'crowd', 'type': 'switch', 'tag': 'c'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
attributes.0.values
  Field required [type=missing, input_value={'name': 'crowd', 'type': 'switch', 'tag': 'c'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.0.subcategories.0.subcategories
  Field required [type=missing, input_value={'name': 'pedestrian'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.0.subcategories.0.color
  Field required [type=missing, input_value={'name': 'pedestrian'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.0.subcategories.1.subcategories
  Field required [type=missing, input_value={'name': 'rider'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.0.subcategories.1.color
  Field required [type=missing, input_value={'name': 'rider'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.0.color
  Field required [type=missing, input_value={'name': 'human', 'subcat...n'}, {'name': 'rider'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.1.subcategories.0.subcategories
  Field required [type=missing, input_value={'name': 'car'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.1.subcategories.0.color
  Field required [type=missing, input_value={'name': 'car'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.1.subcategories.1.subcategories
  Field required [type=missing, input_value={'name': 'truck'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.1.subcategories.1.color
  Field required [type=missing, input_value={'name': 'truck'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.1.subcategories.2.subcategories
  Field required [type=missing, input_value={'name': 'bus'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.1.subcategories.2.color
  Field required [type=missing, input_value={'name': 'bus'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.1.subcategories.3.subcategories
  Field required [type=missing, input_value={'name': 'train'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.1.subcategories.3.color
  Field required [type=missing, input_value={'name': 'train'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.1.color
  Field required [type=missing, input_value={'name': 'vehicle', 'subc...s'}, {'name': 'train'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.2.subcategories.0.subcategories
  Field required [type=missing, input_value={'name': 'motorcycle'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.2.subcategories.0.color
  Field required [type=missing, input_value={'name': 'motorcycle'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.2.subcategories.1.subcategories
  Field required [type=missing, input_value={'name': 'bicycle'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.2.subcategories.1.color
  Field required [type=missing, input_value={'name': 'bicycle'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.2.color
  Field required [type=missing, input_value={'name': 'bike', 'subcate...}, {'name': 'bicycle'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
poseSigmas
  Field required [type=missing, input_value={'image_size': {'height':... {'name': 'bicycle'}]}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
`

**Comment by corfyi** [comment]
I also encountered the same problem. It seems like a bug after some backend changes, because I successfully submitted a month ago, and now submitting the same file gives me the same error as yours.

**Comment by chongweiliu** [comment]
> I also encountered the same problem. It seems like a bug after some backend changes, because I successfully submitted a month ago, and now submitting the same file gives me the same error as yours.

It looks like we can only test on the validation set with the offline testing tool for now, if the bug isn't fixed on the sever.

**Comment by HELLORPG** [comment]
I have a similar issue [here](https://github.com/bdd100k/bdd100k/discussions/327).

**Comment by gchhablani** [comment]
Hi all

This has nothing to do with EvalAI backend.
The error seems to be at the host end with their evaluation script not being updated according because of some package updates.
We have contacted the hosts and waiting for your response.
Thank you for your patience!

**Comment by balabooooo** [comment]
I encountered the same problem with the **offline testing tool**.

` pip install pydantic==1.10.12` works for me.

**Comment by YouKnowT** [comment]
> I encountered the same problem with the **offline testing tool**.
> 
> ` pip install pydantic==1.10.12` works for me.

It works for me, too
